export const PokemonActionTypes = {
    FETCH_ITEMS_REQUEST: 'FETCH_ITEMS_REQUEST',
    FETCH_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCCESS',
    GET_POKEMON_REQUEST: 'GET_POKEMON_REQUEST',
    GET_POKEMON_SUCCESS: 'GET_POKEMON_SUCCESS'
}
